resolved:
- id: 2
  name: UEFA Champions League
  country: World
  type: Cup
  season: 2025
  source: UEFA Champions League
  match_score: 999
  override: true
- id: 3
  name: UEFA Europa League
  country: World
  type: Cup
  season: 2025
  source: UEFA Europa League
  match_score: 999
  override: true
- id: 17
  name: AFC Champions League
  country: World
  type: Cup
  season: 2025
  source: AFC Champions League
  match_score: 999
  override: true
- id: 848
  name: UEFA Europa Conference League
  country: World
  type: Cup
  season: 2025
  source: UEFA Europa Conference League
  match_score: 999
  override: true
- id: 41
  name: League One
  country: England
  type: League
  season: 2025
  source: İngiltere 1. Lig
  match_score: 999
  override: true
- id: 42
  name: League Two
  country: England
  type: League
  season: 2025
  source: İngiltere 2. Lig
  match_score: 999
  override: true
- id: 46
  name: EFL Trophy
  country: England
  type: Cup
  season: 2025
  source: İngiltere EFL Trophy
  match_score: 999
  override: true
- id: 141
  name: Segunda División
  country: Spain
  type: League
  season: 2025
  source: İspanya La Liga 2
  match_score: 999
  override: true
- id: 145
  name: Challenger Pro League
  country: Belgium
  type: League
  season: 2025
  source: Belçika 2. Lig
  match_score: 999
  override: true
- id: 188
  name: A-League
  country: Australia
  type: League
  season: 2025
  source: Avustralya A-Ligi
  match_score: 999
  override: true
- id: 210
  name: HNL
  country: Croatia
  type: League
  season: 2025
  source: Hırvatistan 1. HNL
  match_score: 999
  override: true
- id: 345
  name: Czech Liga
  country: Czech-Republic
  type: League
  season: 2025
  source: Çekya 1. Lig
  match_score: 999
  override: true
- id: 39
  name: Premier League
  country: England
  type: League
  season: 2025
  source: İngiltere Premier Lig
  match_score: 100
- id: 40
  name: Championship
  country: England
  type: League
  season: 2025
  source: İngiltere Championship
  match_score: 100
- id: 61
  name: Ligue 1
  country: France
  type: League
  season: 2025
  source: Fransa Ligue 1
  match_score: 100
- id: 62
  name: Ligue 2
  country: France
  type: League
  season: 2025
  source: Fransa Ligue 2
  match_score: 100
- id: 71
  name: Serie A
  country: Brazil
  type: League
  season: 2026
  source: Brezilya Serie A
  match_score: 100
- id: 475
  name: Paulista - A1
  country: Brazil
  type: League
  season: 2026
  source: Brezilya Paulista A1
  match_score: 100
- id: 624
  name: Carioca - 1
  country: Brazil
  type: League
  season: 2026
  source: Brezilya Carioca 1
  match_score: 100
- id: 78
  name: Bundesliga
  country: Germany
  type: League
  season: 2025
  source: Almanya Bundesliga
  match_score: 100
- id: 79
  name: 2. Bundesliga
  country: Germany
  type: League
  season: 2025
  source: Almanya 2. Bundesliga
  match_score: 100
- id: 80
  name: 3. Liga
  country: Germany
  type: League
  season: 2025
  source: Almanya 3. Liga
  match_score: 100
- id: 135
  name: Serie A
  country: Italy
  type: League
  season: 2025
  source: İtalya Serie A
  match_score: 100
- id: 136
  name: Serie B
  country: Italy
  type: League
  season: 2025
  source: İtalya Serie B
  match_score: 100
- id: 88
  name: Eredivisie
  country: Netherlands
  type: League
  season: 2025
  source: Hollanda Eredivisie
  match_score: 100
- id: 89
  name: Eerste Divisie
  country: Netherlands
  type: League
  season: 2025
  source: Hollanda Eerste Divisie
  match_score: 100
- id: 94
  name: Primeira Liga
  country: Portugal
  type: League
  season: 2025
  source: Portekiz Primeira Liga
  match_score: 100
- id: 95
  name: Segunda Liga
  country: Portugal
  type: League
  season: 2025
  source: Portekiz Segunda Liga
  match_score: 100
- id: 140
  name: La Liga
  country: Spain
  type: League
  season: 2025
  source: İspanya La Liga
  match_score: 100
- id: 179
  name: Premiership
  country: Scotland
  type: League
  season: 2025
  source: İskoçya Premiership
  match_score: 100
- id: 305
  name: Stars League
  country: Qatar
  type: League
  season: 2025
  source: Katar Stars League
  match_score: 100
- id: 518
  name: Reserve Pro League
  country: Belgium
  type: League
  season: 2025
  source: Belçika Pro Lig
  match_score: 80
- id: 333
  name: Premier League
  country: Ukraine
  type: League
  season: 2025
  source: Ukrayna Premier Lig
  match_score: 100
- id: 301
  name: Pro League
  country: United-Arab-Emirates
  type: League
  season: 2025
  source: Birleşik Arap Emirlikleri Pro League
  match_score: 100
- id: 203
  name: Süper Lig
  country: Turkey
  type: League
  season: 2025
  source: Türkiye Süper Lig
  match_score: 100
- id: 204
  name: 1. Lig
  country: Turkey
  type: League
  season: 2025
  source: Türkiye 1. Lig
  match_score: 100
- id: 218
  name: Bundesliga
  country: Austria
  type: League
  season: 2025
  source: Avusturya Bundesliga
  match_score: 100
- id: 219
  name: 2. Liga
  country: Austria
  type: League
  season: 2025
  source: Avusturya 2. Lig
  match_score: 80
- id: 119
  name: Superliga
  country: Denmark
  type: League
  season: 2025
  source: Danimarka Superliga
  match_score: 100
- id: 197
  name: Super League 1
  country: Greece
  type: League
  season: 2025
  source: Yunanistan Süper Lig
  match_score: 80
- id: 253
  name: Major League Soccer
  country: USA
  type: League
  season: 2026
  source: Major League Soccer
  match_score: 100
- id: 207
  name: Super League
  country: Switzerland
  type: League
  season: 2025
  source: İsviçre Süper Lig
  match_score: 100
- id: 409
  name: Premier League
  country: Namibia
  type: League
  season: 2018
  source: Rusya Premier League
  match_score: 80
- id: 262
  name: Liga MX
  country: Mexico
  type: League
  season: 2025
  source: Meksika Liga MX
  match_score: 100
- id: 283
  name: Liga I
  country: Romania
  type: League
  season: 2025
  source: Romanya Liga I
  match_score: 100
- id: 288
  name: Premier Soccer League
  country: South-Africa
  type: League
  season: 2025
  source: Premier Soccer League
  match_score: 100
- id: 307
  name: Pro League
  country: Saudi-Arabia
  type: League
  season: 2025
  source: Suudi Arabistan Pro League
  match_score: 100
- id: 383
  name: Ligat Ha'al
  country: Israel
  type: League
  season: 2025
  source: Ligat Ha'al
  match_score: 100
- id: 106
  name: Ekstraklasa
  country: Poland
  type: League
  season: 2025
  source: Polonya Ekstraklasa
  match_score: 100
- id: 343
  name: First League
  country: Armenia
  type: League
  season: 2025
  source: First League
  match_score: 100
- id: 318
  name: 1. Division
  country: Cyprus
  type: League
  season: 2025
  source: 1. Division
  match_score: 100
- id: 332
  name: Super Liga
  country: Slovakia
  type: League
  season: 2025
  source: Slovakya Super Liga
  match_score: 100
- id: 128
  name: Liga Profesional Argentina
  country: Argentina
  type: League
  season: 2026
  source: Liga Profesional Argentina
  match_score: 100
- id: 344
  name: Primera División
  country: Bolivia
  type: League
  season: 2025
  source: Primera División
  match_score: 100
- id: 239
  name: Primera A
  country: Colombia
  type: League
  season: 2026
  source: Kolombiya Primera A
  match_score: 100
- id: 242
  name: Liga Pro
  country: Ecuador
  type: League
  season: 2026
  source: Ekvador Liga Pro
  match_score: 100
- id: 409
  name: Premier League
  country: Namibia
  type: League
  season: 2018
  source: Premier League
  match_score: 100
- id: 271
  name: NB I
  country: Hungary
  type: League
  season: 2025
  source: Macaristan NB I
  match_score: 100
- id: 323
  name: Indian Super League
  country: India
  type: League
  season: 2025
  source: Indian Super League
  match_score: 100
- id: 758
  name: Premier Division
  country: Gibraltar
  type: League
  season: 2025
  source: İrlanda Premier Division
  match_score: 80
- id: 98
  name: J1 League
  country: Japan
  type: League
  season: 2026
  source: J1 League
  match_score: 100
- id: 281
  name: Primera División
  country: Peru
  type: League
  season: 2026
  source: Peru Primera División
  match_score: 100
- id: 286
  name: Super Liga
  country: Serbia
  type: League
  season: 2025
  source: Sırbistan Superliga
  match_score: 100
- id: 296
  name: Thai League 1
  country: Thailand
  type: League
  season: 2025
  source: Tayland 1. Lig
  match_score: 70
unresolved: []
ts_utc:
  current: 'true'
